### ISSUE TITLE
Please update Minio because of server: Minio version14 can not access by amz s3 java sdk

### ISSUE THREAD

**Issue by N1v0k** [disaster37/alpine-minio#1]
Hi,

Could you update your image, so it uses the most recent version of minio?
I'm using the amazon s3 SDK and there is a bug that makes it un-usable.

Further info:
https://github.com/minio/mc/issues/1220

(I'm using this image with rancher and forking it is not so easy)

Thanks

**Comment by disaster37** [comment]
Hi,

A new image is published on dockerhub.

**Comment by N1v0k** [comment]
You're a hero!
